package engine

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/lib/pq"
	"github.com/xataio/pgroll/pkg/db"
	"github.com/xataio/pgroll/pkg/migrations"
	"github.com/xataio/pgroll/pkg/roll"
	"github.com/xataio/pgroll/pkg/schema"
)

// pgroll runs the statements of a contract or a rollback one by one, each in its own transaction.
// Under live writes that leaves a window (drop a column, then drop the trigger that still refers to
// it) in which every write to the table fails. The integration tests caught it as writer errors.
// So the same statements, still generated by pgroll, are run here inside one transaction:
// writers see the schema before or after, never in between, and a lock timeout undoes everything.

// txDB lets pgroll's actions run on a transaction we own.
type txDB struct{ tx *sql.Tx }

func (t txDB) ExecContext(ctx context.Context, q string, args ...interface{}) (sql.Result, error) {
	return t.tx.ExecContext(ctx, q, args...)
}

func (t txDB) QueryContext(ctx context.Context, q string, args ...interface{}) (*sql.Rows, error) {
	return t.tx.QueryContext(ctx, q, args...)
}

func (t txDB) WithRetryableTransaction(ctx context.Context, f func(context.Context, *sql.Tx) error) error {
	return f(ctx, t.tx)
}

func (t txDB) Close() error { return nil }

func hasCode(err error, code pq.ErrorCode) bool {
	var pqErr *pq.Error
	return errors.As(err, &pqErr) && pqErr.Code == code
}

const (
	lockNotAvailable = "55P03"
	notInTransaction = "25001" // CREATE/DROP INDEX CONCURRENTLY cannot run inside a transaction block
)

// ddlTx runs f in one transaction as the migrator. If a statement cannot get its lock within lock_timeout
// the transaction is rolled back and retried with capped backoff, until `budget` of waiting is spent.
func (e *Engine) ddlTx(ctx context.Context, s Settings, budget time.Duration, f func(conn db.DB) error) error {
	deadline := time.Now().Add(budget)
	for attempt := 0; ; attempt++ {
		err := func() error {
			tx, err := e.db.BeginTx(ctx, nil)
			if err != nil {
				return err
			}
			defer tx.Rollback()
			// application_name marks the session as the migration for the guard; the pgroll setting stops
			// pgroll's event trigger from recording these statements as a hand-made schema change.
			if _, err := tx.ExecContext(ctx, fmt.Sprintf(`SET LOCAL lock_timeout = %d; SET LOCAL search_path TO %s;
				SET LOCAL application_name TO 'pgroll'; SET LOCAL pgroll.no_inferred_migrations TO 'TRUE'`, s.LockTimeoutMs, appSchema)); err != nil {
				return err
			}
			if err := f(txDB{tx}); err != nil {
				return err
			}
			return tx.Commit()
		}()
		if !hasCode(err, lockNotAvailable) {
			return err
		}
		if time.Now().After(deadline) {
			return fmt.Errorf("could not get the table lock within %.0f s; a long-running transaction is holding it", budget.Seconds())
		}
		if err := sleep(ctx, min(100*time.Millisecond<<min(attempt, 5), 2*time.Second)); err != nil {
			return err
		}
	}
}

// probeLock proves an exclusive lock on the table can be had right now, without changing anything.
func (e *Engine) probeLock(ctx context.Context, table string, s Settings) error {
	err := e.ddlTx(ctx, s, time.Duration(s.LockBudgetS)*time.Second, func(conn db.DB) error {
		_, err := conn.ExecContext(ctx, `LOCK TABLE `+pq.QuoteIdentifier(table)+` IN ACCESS EXCLUSIVE MODE`)
		return err
	})
	if err != nil {
		return fmt.Errorf("could not lock %s: %w", table, err)
	}
	return nil
}

// prevalidate validates the NOT VALID constraints the expand phase added, outside the contract transaction.
// VALIDATE scans the table but only takes SHARE UPDATE EXCLUSIVE, so writers are not blocked while it runs,
// and the contract transaction then finds them already valid and holds its exclusive lock for an instant.
func (e *Engine) prevalidate(ctx context.Context, tables []string) error {
	for _, t := range tables {
		rows, err := e.db.QueryContext(ctx, `SELECT conname FROM pg_constraint WHERE conrelid = to_regclass($1) AND NOT convalidated`, appSchema+"."+pq.QuoteIdentifier(t))
		if err != nil {
			return err
		}
		var names []string
		for rows.Next() {
			var n string
			if err := rows.Scan(&n); err != nil {
				rows.Close()
				return err
			}
			names = append(names, n)
		}
		rows.Close()
		for _, n := range names {
			if _, err := e.db.ExecContext(ctx, `ALTER TABLE `+appSchema+`.`+pq.QuoteIdentifier(t)+` VALIDATE CONSTRAINT `+pq.QuoteIdentifier(n)); err != nil {
				return fmt.Errorf("validate %s.%s: %w", t, n, err)
			}
		}
	}
	return nil
}

// completeAtomically is pgroll's Complete with every statement in one transaction. It reports false when the
// migration cannot be done that way, in which case nothing has changed and pgroll's own Complete should run.
func (e *Engine) completeAtomically(ctx context.Context, run Run, m *roll.Roll, mig *migrations.Migration) (bool, error) {
	for _, op := range mig.Operations {
		if _, ok := op.(migrations.RequiresSchemaRefreshOperation); ok { // raw SQL: pgroll must rebuild the views afterwards
			return false, nil
		}
	}
	if err := e.prevalidate(ctx, opTables(run.Operations)); err != nil {
		return true, err
	}
	st := m.State()
	err := e.ddlTx(ctx, run.Settings, time.Duration(run.Settings.LockBudgetS)*time.Second, func(conn db.DB) error {
		prev, err := st.PreviousVersion(ctx, appSchema)
		if err != nil {
			return err
		}
		if prev != nil {
			if _, err := conn.ExecContext(ctx, `DROP SCHEMA IF EXISTS `+pq.QuoteIdentifier(roll.VersionedSchemaName(appSchema, *prev))+` CASCADE`); err != nil {
				return err
			}
		}
		current, err := st.ReadSchema(ctx, appSchema)
		if err != nil {
			return err
		}
		var actions []migrations.DBAction
		for _, op := range mig.Operations {
			a, err := op.Complete(migrations.NewNoopLogger(), conn, current)
			if err != nil {
				return err
			}
			actions = append(actions, a...)
		}
		return migrations.NewCoordinator(actions).Execute(ctx)
	})
	if hasCode(err, notInTransaction) {
		return false, nil
	}
	if err != nil {
		return true, err
	}
	return true, st.Complete(ctx, appSchema, mig.Name)
}

// rollbackAtomically is pgroll's Rollback with every statement in one transaction; see completeAtomically.
func (e *Engine) rollbackAtomically(ctx context.Context, run Run, m *roll.Roll, mig *migrations.Migration) (bool, error) {
	st := m.State()
	// A revert has to get through eventually, so it may wait for locks far longer than a forward step.
	err := e.ddlTx(ctx, run.Settings, 10*time.Minute, func(conn db.DB) error {
		version := roll.VersionedSchemaName(appSchema, mig.VersionSchemaName())
		if _, err := conn.ExecContext(ctx, `DROP SCHEMA IF EXISTS `+pq.QuoteIdentifier(version)+` CASCADE`); err != nil {
			return err
		}
		before := schema.New()
		prev, err := st.PreviousMigration(ctx, appSchema)
		if err != nil {
			return err
		}
		if prev != nil {
			if before, err = st.SchemaAfterMigration(ctx, appSchema, *prev); err != nil {
				return err
			}
		}
		if err := mig.UpdateVirtualSchema(ctx, before); err != nil {
			return err
		}
		for i := len(mig.Operations) - 1; i >= 0; i-- {
			actions, err := mig.Operations[i].Rollback(migrations.NewNoopLogger(), conn, before)
			if err != nil {
				return err
			}
			if err := migrations.NewCoordinator(actions).Execute(ctx); err != nil {
				return err
			}
		}
		return nil
	})
	if hasCode(err, notInTransaction) {
		return false, nil
	}
	if err != nil {
		return true, err
	}
	return true, st.Rollback(ctx, appSchema, mig.Name)
}
