"""Profile raw event files before trusting them: `wrapped profile` writes docs/data-profile.md.

Reads the raw lines themselves, not the validated bronze, because the point is to see what the
source really sends: nulls, cardinality, formats, duplicates, skew, and schema drift between files.
Plain streaming Python; a 150 MB hour (280k events, 1.1 GB decompressed) takes about a minute.
"""

from __future__ import annotations

import gzip
import json
import re
from collections import Counter
from pathlib import Path
from typing import Any

WATCHED_PAYLOADS = ("PushEvent", "PullRequestEvent", "CreateEvent", "IssuesEvent")


def profile_file(path: Path) -> dict[str, Any]:
    lines = malformed = duplicate_ids = with_org = max_line = 0
    types: Counter[str] = Counter()
    nulls: Counter[str] = Counter()
    ts_formats: Counter[str] = Counter()
    id_formats: Counter[str] = Counter()
    hours: Counter[str] = Counter()
    actors: Counter[int] = Counter()
    logins: dict[int, str] = {}
    payload_keys: dict[str, set[str]] = {t: set() for t in WATCHED_PAYLOADS}
    seen: set[str] = set()
    unreadable = None
    try:
        with gzip.open(path, "rt", encoding="utf-8", errors="replace") as fh:
            for line in fh:
                lines += 1
                max_line = max(max_line, len(line))
                try:
                    event = json.loads(line)
                except ValueError:
                    malformed += 1
                    continue
                event_id = event.get("id")
                id_formats[
                    "digit string" if isinstance(event_id, str) and event_id.isdigit() else type(event_id).__name__
                ] += 1
                if event_id in seen:
                    duplicate_ids += 1
                seen.add(event_id)
                event_type = event.get("type")
                types[event_type] += 1
                actor, repo = event.get("actor") or {}, event.get("repo") or {}
                for field, value in (("id", event_id), ("type", event_type), ("actor.id", actor.get("id")),
                                     ("actor.login", actor.get("login")), ("repo.id", repo.get("id")),
                                     ("repo.name", repo.get("name")), ("created_at", event.get("created_at"))):  # fmt: skip
                    if value in (None, ""):
                        nulls[field] += 1
                with_org += "org" in event
                created = str(event.get("created_at") or "")
                ts_formats[re.sub(r"\d", "9", created)] += 1
                hours[created[:13]] += 1
                if actor.get("id") is not None:
                    actors[actor["id"]] += 1
                    logins[actor["id"]] = str(actor.get("login"))
                if event_type in payload_keys:
                    payload_keys[event_type] |= set(event.get("payload") or {})
    except (OSError, EOFError) as exc:
        unreadable = f"{type(exc).__name__}: {exc}"

    counts = sorted(actors.values(), reverse=True)
    events = sum(counts)
    bot_events = sum(n for a, n in actors.items() if logins[a].endswith("[bot]"))
    return {
        "file": path.name, "bytes": path.stat().st_size, "unreadable": unreadable, "lines": lines, "malformed": malformed,
        "duplicate_ids": duplicate_ids, "max_line_chars": max_line, "id_formats": dict(id_formats), "nulls": dict(nulls),
        "timestamp_formats": dict(ts_formats), "hours_covered": sorted(hours), "with_org": with_org,
        "types": types.most_common(), "actors": len(actors), "bot_events": bot_events, "events": events,
        # Bots are named; people are not. A profile is no place to publish who was busiest.
        "top_actors": [
            (logins[a] if logins[a].endswith("[bot]") else "(account without a bot label)", n)
            for a, n in actors.most_common(5)
        ],
        "one_event_actors": sum(1 for n in counts if n == 1),
        "p50": counts[len(counts) // 2] if counts else 0, "p90": counts[len(counts) // 10] if counts else 0,
        "p99": counts[len(counts) // 100] if counts else 0, "max": counts[0] if counts else 0,
        "payload_keys": {t: sorted(k) for t, k in payload_keys.items()},
    }  # fmt: skip


def _pct(part: int, whole: int) -> str:
    if not whole:
        return "n/a"
    return "<0.1%" if 0 < part / whole < 0.0005 else f"{100 * part / whole:.1f}%"


def render(profiles: list[dict[str, Any]], source: str) -> str:
    out = [
        "# Data profile",
        "",
        f"Generated by `wrapped profile` from the raw files in {source}. This is what the source sends, measured before",
        "validation. The schema, the validation rules and the generator's shape were designed from these numbers.",
        "",
        "## Files",
        "",
        "| File | Size | Lines | Malformed lines | Duplicate ids | Longest line | Hours covered |",
        "|---|---:|---:|---:|---:|---:|---|",
    ]
    readable = [p for p in profiles if not p["unreadable"]]
    for p in profiles:
        if p["unreadable"]:
            out.append(f"| `{p['file']}` | {p['bytes'] / 1e6:.1f} MB | unreadable: {p['unreadable']} | | | | |")
        else:
            out.append(
                f"| `{p['file']}` | {p['bytes'] / 1e6:.1f} MB | {p['lines']:,} | {p['malformed']:,} | {p['duplicate_ids']:,} "
                f"| {p['max_line_chars']:,} chars | {', '.join(p['hours_covered'])} |"
            )
    out += ["", "## Nulls, formats, encoding", "",
            "| File | Null or empty fields | Event id format | Timestamp formats | Events with an `org` |", "|---|---|---|---|---:|"]  # fmt: skip
    for p in readable:
        nulls = ", ".join(f"{k}: {v:,}" for k, v in p["nulls"].items()) or "none"
        ids = ", ".join(f"{k}: {v:,}" for k, v in p["id_formats"].items())
        stamps = ", ".join(f"`{k}`: {v:,}" for k, v in p["timestamp_formats"].items())
        out.append(f"| `{p['file']}` | {nulls} | {ids} | {stamps} | {_pct(p['with_org'], p['lines'])} |")
    out += ["", "## Cardinality and skew", "",
            "| File | Distinct actors | Actors with exactly 1 event | p50 / p90 / p99 / max events per actor | Events from `[bot]` logins |",
            "|---|---:|---:|---|---:|"]  # fmt: skip
    for p in readable:
        out.append(
            f"| `{p['file']}` | {p['actors']:,} | {_pct(p['one_event_actors'], p['actors'])} "
            f"| {p['p50']} / {p['p90']} / {p['p99']} / {p['max']:,} | {_pct(p['bot_events'], p['events'])} |"
        )
    out += ["", "Busiest accounts per file (login, events):", ""]
    for p in readable:
        out.append(f"- `{p['file']}`: " + ", ".join(f"{login} {n:,}" for login, n in p["top_actors"]))
    out += ["", "## Event-type mix", ""]
    names = sorted(
        {t for p in readable for t, _ in p["types"]}, key=lambda t: -max(dict(p["types"]).get(t, 0) for p in readable)
    )
    out += [
        "| Event type | " + " | ".join(f"`{p['file']}`" for p in readable) + " |",
        "|---|" + "---:|" * len(readable),
    ]
    for name in names:
        cells = [
            _pct(dict(p["types"]).get(name, 0), p["lines"]) if dict(p["types"]).get(name) else "absent"
            for p in readable
        ]
        out.append(f"| {name} | " + " | ".join(cells) + " |")
    out += [
        "",
        "## Schema drift between files",
        "",
        "Top-level keys present in the payload of each event type, per file.",
        "",
    ]
    for event_type in WATCHED_PAYLOADS:
        out.append(f"**{event_type}**")
        out.append("")
        for p in readable:
            out.append(f"- `{p['file']}`: {', '.join(f'`{k}`' for k in p['payload_keys'][event_type]) or '(none)'}")
        out.append("")
    return "\n".join(out)


def profile(raw_dir: Path, limit: int = 12) -> str:
    """Profile up to `limit` files, spread evenly across the directory's (chronological) file names."""
    files = sorted(raw_dir.glob("*.json.gz"))
    if len(files) > limit:
        step = len(files) / limit
        files = [files[int(i * step)] for i in range(limit)]
    return render([profile_file(f) for f in files], f"`{raw_dir.name}/`")
