/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: the process is up */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: exercises PostgreSQL and checks data freshness */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics */
        get: operations["prom_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index series (latest vintage, or as of a time) */
        get: operations["get_index_v1_index_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/index/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every published vintage of one index value (audit trail) */
        get: operations["get_revisions_v1_index_revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inflation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inflation rate over a rolling window */
        get: operations["get_inflation_v1_inflation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inflation/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest inflation rate for every server x division */
        get: operations["get_inflation_matrix_v1_inflation_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/manipulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manipulation / thin-market events for a server, newest first (keyset-paginated) */
        get: operations["list_manipulation_v1_manipulation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/money-flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Currency sinks and faucets per day */
        get: operations["money_flows_v1_money_flows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Patch timeline (keyset-paginated) */
        get: operations["list_patches_v1_patches_get"];
        put?: never;
        /** Record a patch note (auth: patches:write; Idempotency-Key required) */
        post: operations["create_patch_v1_patches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/purchasing-power": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What an hour of an activity buys over time (labour-hours) */
        get: operations["purchasing_power_v1_purchasing_power_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detected shocks with patch attribution */
        get: operations["list_shocks_v1_shocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worlds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Worlds, servers, divisions, activities */
        get: operations["worlds_v1_worlds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityOut */
        ActivityOut: {
            /** Activity Id */
            activity_id: string;
            /** Label */
            label: string;
        };
        /** Attribution */
        Attribution: {
            /** Lag Hours */
            lag_hours: number;
            /** Patch Id */
            patch_id: string;
            /** Rank */
            rank: number;
            /**
             * Released At
             * Format: date-time
             */
            released_at: string;
            /** Relevance */
            relevance: number;
            /** Title */
            title: string;
        };
        /** DivisionOut */
        DivisionOut: {
            /** Division Id */
            division_id: string;
            /** Label */
            label: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @example not_found
             */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            }[] | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** FlowPoint */
        FlowPoint: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /**
             * Faucets
             * @description null when the world has no faucet feed (real EVE)
             */
            faucets: number | null;
            /**
             * Net
             * @description faucets - sinks: positive = currency supply growing
             */
            net: number | null;
            /** Sinks */
            sinks: number;
        };
        /** FlowsResponse */
        FlowsResponse: {
            /** Methods */
            methods: {
                [key: string]: string;
            };
            /** Points */
            points: components["schemas"]["FlowPoint"][];
            /** Server Id */
            server_id: string;
            /** World Id */
            world_id: string;
        };
        /** Freshness */
        Freshness: {
            /** Age Hours */
            age_hours: number | null;
            /** Last Day */
            last_day: string | null;
            /**
             * Stale
             * @description true when the newest published day is older than the freshness SLO
             */
            stale: boolean;
        };
        /** IndexPoint */
        IndexPoint: {
            /**
             * Coverage
             * @description share of basket weight with an observed price that day
             */
            coverage: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Revised */
            revised: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "partial" | "insufficient";
            /**
             * Value
             * @description index level; null when coverage is insufficient (never extrapolated)
             */
            value: number | null;
            /**
             * Vintage
             * @description 1 = first publication; >1 = revised by late or corrected data
             */
            vintage: number;
        };
        /** IndexResponse */
        IndexResponse: {
            /**
             * As Of
             * @description when set, values as they were published at that instant
             */
            as_of: string | null;
            freshness: components["schemas"]["Freshness"];
            /** Method Version */
            method_version: string | null;
            /** Points */
            points: components["schemas"]["IndexPoint"][];
            series: components["schemas"]["SeriesRef"];
        };
        /** InflationCell */
        InflationCell: {
            /** Annualized */
            annualized: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Division Id */
            division_id: string;
            /** Rate */
            rate: number;
            /** Server Id */
            server_id: string;
        };
        /** InflationMatrix */
        InflationMatrix: {
            /** Cells */
            cells: components["schemas"]["InflationCell"][];
            /** Window Days */
            window_days: number;
            /** World Id */
            world_id: string;
        };
        /** InflationPoint */
        InflationPoint: {
            /** Annualized */
            annualized: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            /**
             * Rate
             * @description change over the window, e.g. 0.02 = +2%
             */
            rate: number;
        };
        /** InflationResponse */
        InflationResponse: {
            /** Points */
            points: components["schemas"]["InflationPoint"][];
            series: components["schemas"]["SeriesRef"];
            /** Window Days */
            window_days: number;
        };
        /** ItemOut */
        ItemOut: {
            /** Division Id */
            division_id: string;
            /** Item Id */
            item_id: number;
            /** Name */
            name: string;
        };
        /** ItemPower */
        ItemPower: {
            /** Hours Per Unit */
            hours_per_unit: number | null;
            /** Item Id */
            item_id: number;
            /** Price */
            price: number | null;
            /** Units Per Hour */
            units_per_hour: number | null;
        };
        /** ManipulationOut */
        ManipulationOut: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Item Id */
            item_id: number;
            /** Item Name */
            item_name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "extreme_listing" | "hampel_reject" | "thin_market_spike";
            /** N Obs */
            n_obs: number;
            /** Server Id */
            server_id: string;
            /** Severity */
            severity: number;
            /** Thin */
            thin: boolean;
        };
        /** ManipulationPage */
        ManipulationPage: {
            /** Items */
            items: components["schemas"]["ManipulationOut"][];
            page: components["schemas"]["Page"];
        };
        /** Page */
        Page: {
            /** Limit */
            limit: number;
            /**
             * Next Cursor
             * @description opaque; pass back as ?cursor= to get the next page
             */
            next_cursor: string | null;
        };
        /** PatchImpact */
        PatchImpact: {
            /** Log Change */
            log_change: number;
            /** Robust Z */
            robust_z: number;
        };
        /** PatchIn */
        PatchIn: {
            /**
             * Is Major
             * @default false
             */
            is_major: boolean;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Patch Id */
            patch_id: string;
            /**
             * Released At
             * Format: date-time
             */
            released_at: string;
            /** Title */
            title: string;
            /** Version */
            version?: string | null;
            /** World Id */
            world_id: string;
        };
        /** PatchOut */
        PatchOut: {
            /** @description headline index move in the 7 days after vs before release */
            impact: components["schemas"]["PatchImpact"] | null;
            /** Is Major */
            is_major: boolean;
            /** Notes Excerpt */
            notes_excerpt: string;
            /** Patch Id */
            patch_id: string;
            /**
             * Released At
             * Format: date-time
             */
            released_at: string;
            /** Source */
            source: string;
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
            /** Version */
            version: string | null;
            /** World Id */
            world_id: string;
        };
        /** PatchPage */
        PatchPage: {
            /** Items */
            items: components["schemas"]["PatchOut"][];
            page: components["schemas"]["Page"];
        };
        /** PowerPoint */
        PowerPoint: {
            /**
             * Basket Cost
             * @description cost that day of the basket that cost 1,000,000 at the index reference
             */
            basket_cost: number | null;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Hours Per Basket */
            hours_per_basket: number | null;
            /** Items */
            items: components["schemas"]["ItemPower"][];
            /**
             * Real Wage
             * @description wage deflated by the server index (reference-period currency)
             */
            real_wage: number | null;
            /**
             * Wage
             * @description currency earned per hour (nominal bounty + yields at that day's prices)
             */
            wage: number | null;
            /** Wage Goods */
            wage_goods: number | null;
            /** Wage Isk */
            wage_isk: number;
        };
        /** PurchasingPowerResponse */
        PurchasingPowerResponse: {
            activity: components["schemas"]["ActivityOut"];
            /** Items */
            items: components["schemas"]["ItemOut"][];
            /** Points */
            points: components["schemas"]["PowerPoint"][];
            /** Rates */
            rates: components["schemas"]["WageRate"][];
            /** Server Id */
            server_id: string;
            /** World Id */
            world_id: string;
            /** Yields */
            yields: components["schemas"]["Yield"][];
        };
        /** Revision */
        Revision: {
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Coverage */
            coverage: number;
            /** Input Hash */
            input_hash: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "initial" | "late_data" | "source_revision" | "method_change";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "partial" | "insufficient";
            /** Value */
            value: number | null;
            /** Vintage */
            vintage: number;
        };
        /** RevisionsResponse */
        RevisionsResponse: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Revisions */
            revisions: components["schemas"]["Revision"][];
            series: components["schemas"]["SeriesRef"];
        };
        /** SeriesRef */
        SeriesRef: {
            /**
             * Division Id
             * @description 'all' for the headline index
             */
            division_id: string;
            /** Series Id */
            series_id: number;
            /**
             * Server Id
             * @description 'all' for the cross-server index
             */
            server_id: string;
            /** World Id */
            world_id: string;
        };
        /** ServerOut */
        ServerOut: {
            /** Name */
            name: string;
            /** Server Id */
            server_id: string;
        };
        /** ShockOut */
        ShockOut: {
            /**
             * Attributions
             * @description empty = unattributed: no patch in the lookback window
             */
            attributions: components["schemas"]["Attribution"][];
            /**
             * Day
             * Format: date
             */
            day: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down";
            /** Log Change */
            log_change: number;
            /**
             * Persistence
             * @description share of the move still present 3 days later; null = not yet known
             */
            persistence: number | null;
            /** Robust Z */
            robust_z: number;
        };
        /** ShocksResponse */
        ShocksResponse: {
            series: components["schemas"]["SeriesRef"];
            /** Shocks */
            shocks: components["schemas"]["ShockOut"][];
        };
        /** WageRate */
        WageRate: {
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Isk Per Hour */
            isk_per_hour: number;
        };
        /** WorldOut */
        WorldOut: {
            /** Activities */
            activities: components["schemas"]["ActivityOut"][];
            /** Currency */
            currency: string;
            /** Divisions */
            divisions: components["schemas"]["DivisionOut"][];
            /** First Day */
            first_day: string | null;
            freshness: components["schemas"]["Freshness"];
            /** Is Synthetic */
            is_synthetic: boolean;
            /** Items */
            items: components["schemas"]["ItemOut"][];
            /** Name */
            name: string;
            /**
             * Price Source
             * @enum {string}
             */
            price_source: "snapshots" | "trade_history";
            /** Servers */
            servers: components["schemas"]["ServerOut"][];
            /** World Id */
            world_id: string;
        };
        /** Yield */
        Yield: {
            /** Item Id */
            item_id: number;
            /** Name */
            name: string;
            /** Qty Per Hour */
            qty_per_hour: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    prom_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_index_v1_index_get: {
        parameters: {
            query: {
                world: string;
                /** @description server id, or 'all' */
                server?: string;
                /** @description division id, or 'all' */
                division?: string;
                from?: string | null;
                to?: string | null;
                /** @description ISO time: reproduce what was published then */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_revisions_v1_index_revisions_get: {
        parameters: {
            query: {
                world: string;
                day: string;
                /** @description server id, or 'all' */
                server?: string;
                /** @description division id, or 'all' */
                division?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_inflation_v1_inflation_get: {
        parameters: {
            query: {
                world: string;
                /** @description server id, or 'all' */
                server?: string;
                /** @description division id, or 'all' */
                division?: string;
                /** @description 7, 30, 90 or 365 days */
                window?: number;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InflationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_inflation_matrix_v1_inflation_matrix_get: {
        parameters: {
            query: {
                world: string;
                window?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InflationMatrix"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_manipulation_v1_manipulation_get: {
        parameters: {
            query: {
                world: string;
                server: string;
                kind?: string | null;
                min_severity?: number;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManipulationPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    money_flows_v1_money_flows_get: {
        parameters: {
            query: {
                world: string;
                server: string;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_patches_v1_patches_get: {
        parameters: {
            query: {
                world: string;
                from?: string | null;
                to?: string | null;
                major_only?: boolean;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_patch_v1_patches_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchIn"];
            };
        };
        responses: {
            /** @description idempotent replay of an earlier identical request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description missing/invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description missing scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description idempotency key reused with a different body, or patch exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    purchasing_power_v1_purchasing_power_get: {
        parameters: {
            query: {
                world: string;
                server: string;
                activity: string;
                /** @description up to 10 item ids */
                items?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchasingPowerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_shocks_v1_shocks_get: {
        parameters: {
            query: {
                world: string;
                /** @description server id, or 'all' */
                server?: string;
                /** @description division id, or 'all' */
                division?: string;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShocksResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    worlds_v1_worlds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldOut"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
